config/routes.rb
Broker88::Application.routes.draw do
  root :to => 'carriers#index'

  resources :carriers, :customers, :shippers

  resources :loads do
    get :autocomplete_carrier_name, :on => :collection
    get :autocomplete_customer_name, :on => :collection
    get :autocomplete_shipper_name, :on => :collection
  end

  resources :import do
    get :carrier
    get :load
    get :customer
  end 

end

app/models/load.rb
class Load
	include Mongoid::Document
	field :load_number
	key   :load_number

	field :carrier_name
	field :customer_name
	field :carrier_id
	field :customer_id
	field :location_id
	field :claim_id
	field :charge_id
	field :carrier_rate
	field :customer_rate
	field :temp
	field :driver_cell
	field :customer_currency
	field :carrier_currency
	field :customer_po
	field :created_at, :type => DateTime
	field :updated_at, :type => DateTime

	references_many :shippers
	references_many :customers
	references_many :carriers

	embeds_many :picks
	embeds_many :drops

	accepts_nested_attributes_for :picks
	accepts_nested_attributes_for :drops

	before_create :create_load_number

	private
		def create_load_number
			@loadnumber = Load.max("load_number").to_i + 1
			self.load_number = @loadnumber.to_s
		end
end

app/controllers/loads_controller.rb
class LoadsController < ApplicationController
	autocomplete :carrier, :name
	autocomplete :customer, :name
	autocomplete :shipper, :name
	def index
		@loads = Load.any_of({:load_number => Regexp.new("^#{params[:search]}.*", true)}, {:carrier_name => Regexp.new("^#{params[:search]}.*", true)}, {:customer_name => Regexp.new("^#{params[:search]}.*", true)})
		@load = @loads.first
	end

	def new
		@loads = Load.all
		@load = Load.new
		@pick = @load.picks.build()
		@drop = @load.drops.build()
		@pick_item = @pick.pick_items.build()
		#@drop.drop_items.build()
	end

	def show
		@loads = Load.all
		@load = Load.find(params[:id])
	end

	def create
		@load = Load.new(params[:load])

		if @load.save
			redirect_to loads_path, notice: 'New load created!'
		else
			render :action => 'new'
		end
	end
end

app/helpers/loads_helper.rb
module LoadsHelper
end

app/views/loads/index.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Load #
				%th Carrier
				%th Carrier Rate
				%th Customer
				%th Customer Rate
				%th
		%tbody
			- @loads.each do |load|
				%tr{:data => {"record_id" => load.id}}
					%td= load.load_number
					%td= load.carrier_name
					%td= load.carrier_rate
					%td= load.customer_name
					%td= load.customer_rate
					%td
						= link_to load_path(load), :class => 'pjax'  do
							%i.icon-search
						= link_to load_path(load), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		- if @load.nil?
			.alert.alert-error
				No Results
				.pull-right= link_to 'Clear Search', loads_path
		-else
			.well-header
				= @load.load_number
			.well
				.row-fluid
					.span6
						.field
							%b Customer
							%br
							= @load.customer_name
						.field
							%b Carrier Rate
							%br
							= @load.customer_rate
						.field
							%b Driver Cell
							%br
							= @load.driver_cell
					.span6
						.field
							%b Carrier
							%br
							= @load.carrier_name
						.field
							%b Carrier Rate
							%br
							= @load.carrier_rate
						.field
							%b Driver Cell
							%br
							= @load.driver_cell

app/views/loads/new.html.haml
.row-fluid
	.span12
		= nested_form_for @load do |f|
			.row-fluid
				.span6
					.well-header
						New Load
					.well
						.row-fluid
							.span6
								.field
									= f.label :customer_name
									= f.autocomplete_field :customer_name, autocomplete_customer_name_loads_path, :update_elements => {:id => "#load_customer_id_field"}
									= f.hidden_field :customer_id, :id => 'load_customer_id_field'
									= f.label :customer_rate
									= f.text_field :customer_rate
							.span6
								.field
									= f.label :carrier_name
									= f.autocomplete_field :carrier_name, autocomplete_carrier_name_loads_path, :update_elements => {:id => "#load_carrier_id_field"}
									= f.hidden_field :carrier_id, :id => 'load_carrier_id_field'
									= f.label :carrier_rate
									= f.text_field :carrier_rate
			.row-fluid						
				.span6
					= f.link_to_add "Add Pick", :picks, :node => "#pickadd", :position => :before, :type => 'outer'
					= f.fields_for :picks do |p|			
						.row-fluid
							.span12
								.well-header
									Picks
									.pull-right
										= p.link_to_remove do
											%i.icon-remove
								.well
									.row-fluid
										.span6
											.field
												= p.label :date
												= p.text_field :date
										.span6
											.field
												= p.label :pick_up_number
												= p.text_field :pick_up_number
									.heading.row-fluid
										.span2 Amount
										.span4 Unit
										.span6
											.row-fluid
												.span11.field
													Commodity
												.field.pull-right
													= p.link_to_add :pick_items, :node => "#pick_item_add", :position => :before, :type => 'inner' do
														%i.icon-plus
									= p.fields_for :pick_items do |pi|
										.loaditem.row-fluid
											.span2= pi.text_field :amount
											.span4= pi.text_field :unit
											.span6
												.row-fluid
													.span11.field
														= pi.text_field :commodity
													.field.pull-right
														= pi.link_to_remove do
															%i.icon-remove
									#pick_item_add

					#pickadd
				.span6
					= f.link_to_add "Add Drop", :drops, :node => "#dropadd", :position => :before, :type => 'outer'
					= f.fields_for :drops do |d|
						.row-fluid
							.span12
								.well-header
									Drops
									.pull-right
										= d.link_to_remove do
											%i.icon-remove
								.well
									.row-fluid
										.span6
											.field
												= d.label :date
												= d.text_field :date
										.span6
											.field
												= d.label :po_number
												= d.text_field :po_number

					#dropadd
			.well-header
				.row-fluid
					.span10
						%br
					.span2
						.pull-right
							= link_to loads_path do 
								%span.btn Cancel
							= f.submit 'Save Load', :class => 'btn'

app/views/loads/show.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Load #
				%th Carrier
				%th Carrier Rate
				%th Customer
				%th Customer Rate
				%th
		%tbody
			- @loads.each do |load|
				%tr
					%td= load.load_number
					%td= load.carrier_name
					%td= load.carrier_rate
					%td= load.customer_name
					%td= load.customer_rate
					%td
						= link_to load_path(load), :class => 'pjax'  do
							%i.icon-search
						= link_to load_path(load), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		- if @load.nil?
			.alert.alert-error
				No Results
				.pull-right= link_to 'Clear Search', loads_path
		-else
			.well-header
				= @load.load_number
			.well
				.row-fluid
					.span6
						.field
							%b Customer
							%br
							= @load.customer_name
						.field
							%b Carrier Rate
							%br
							= @load.customer_rate
						.field
							%b Driver Cell
							%br
							= @load.driver_cell
					.span6
						.field
							%b Carrier
							%br
							= @load.carrier_name
						.field
							%b Carrier Rate
							%br
							= @load.carrier_rate
						.field
							%b Driver Cell
							%br
							= @load.driver_cell