config/routes.rb
Broker88::Application.routes.draw do
  root :to => 'carriers#index'

  resources :carriers, :customers, :shippers

  resources :loads do
    get :autocomplete_carrier_name, :on => :collection
    get :autocomplete_customer_name, :on => :collection
    get :autocomplete_shipper_name, :on => :collection
  end

  resources :import do
    get :carrier
    get :load
    get :customer
  end 

end

app/models/customer.rb
class Customer
	include Mongoid::Document
	field :name
	field :street_address
	field :unit_number
	field :city
	field :state
	field :country
	field :postal_code
	field :contact_id
	field :status
	field :phone_number
	field :toll_free
	field :fax_number
	field :email
	field :created_at, :type => DateTime
	field :updated_at, :type => DateTime

	referenced_in :load
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customers = Customer.any_of({:name => Regexp.new("^#{params[:search]}.*", true)})
		@customer = @customers.first
	end

	def new
		@customers = Customer.all
		@customer = Customer.new
	end

	def show
		@customers = Customer.all
		@customer = Customer.find(params[:id])
	end

	def create
		@customer = Customer.new(params[:customer])

		if @customer.save
			redirect_to customers_path, notice: 'Customer successfully created!'
		else
			render :action => 'new'
		end
	end

	def destroy
		@customer = Customer.find(params[:id])

		@customer.destroy
		redirect_to customers_path, notice: 'Customer deleted'
	end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Name
				%th City
				%th State
				%th Phone Number
				%th Toll Free
				%th Fax Number
				%th
		%tbody
			- @customers.each do |customer|
				%tr
					%td= customer.name
					%td= customer.city
					%td= customer.state
					%td= customer.phone_number
					%td= customer.toll_free
					%td= customer.fax_number
					%td
						= link_to customer_path(customer), :class => 'pjax'  do
							%i.icon-search
						= link_to customer_path(customer), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		- if @customer.nil?
			.alert.alert-error
				No Results
				.pull-right= link_to 'Clear Search', customers_path
		-else
			.well-header
				= @customer.name
			.well
				.row-fluid
					.span6
						.field
							%b Unit #
							%br
							= @customer.unit_number
						.field
							%b City
							%br
							= @customer.city
						.field
							%b Country
							%br
							= @customer.country
					.span6
						.field
							%b Address
							%br
							= @customer.street_address
						.field
							%b State
							%br
							= @customer.state
						.field
							%b Postal Code
							%br
							= @customer.postal_code

app/views/customers/new.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Name
				%th City
				%th State
				%th Phone Number
				%th Toll Free
				%th Fax Number
				%th
		%tbody
			- @customers.each do |customer|
				%tr
					%td= customer.name
					%td= customer.city
					%td= customer.state
					%td= customer.phone_number
					%td= customer.toll_free
					%td= customer.fax_number
					%td
						= link_to customer_path(customer), :class => 'pjax' do
							%i.icon-search
						= link_to customer_path(customer), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		.well-header
			New customer
		.well
			= form_for @customer do |f|
				.row-fluid
					.span6
						.field
							= f.label :status
							= f.text_field :status
				.row-fluid
					.span12
						.field.full
							= f.label :name
							= f.text_field :name
				.row-fluid
					.span6
						.field
							= f.label :phone_number
							= f.text_field :phone_number
						.field
							= f.label :toll_free
							= f.text_field :toll_free
						.field
							= f.label :unit_number
							= f.text_field :unit_number
						.field
							= f.label :city
							= f.text_field :city
						.field
							= f.label :country
							= f.text_field :country
					.span6
						.field
							= f.label :fax_number
							= f.text_field :fax_number
						.field
							= f.label :email
							= f.text_field :email
						.field
							= f.label :street_address
							= f.text_field :street_address
						.field
							= f.label :state
							= f.text_field :state
						.field
							= f.label :postal_code
							= f.text_field :postal_code
				%br
				.row-fluid
					.span8
						%br
					.span4
						.actions
							= f.submit 'Save', :class => 'btn btn-primary'
							= link_to :action => "index" do
								%span.btn.btn-primary Cancel

app/views/customers/show.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Name
				%th City
				%th State
				%th Phone Number
				%th Toll Free
				%th Fax Number
				%th
		%tbody
			- @customers.each do |customer|
				%tr
					%td= customer.name
					%td= customer.city
					%td= customer.state
					%td= customer.phone_number
					%td= customer.toll_free
					%td= customer.fax_number
					%td
						= link_to customer_path(customer), :class => 'pjax'  do
							%i.icon-search
						= link_to customer_path(customer), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		.well-header
			= @customer.name
		.well
			.row-fluid
				.span6
					.field
						%b Unit #
						%br
						= @customer.unit_number
					.field
						%b City
						%br
						= @customer.city
					.field
						%b Country
						%br
						= @customer.country
				.span6
					.field
						%b Address
						%br
						= @customer.street_address
					.field
						%b State
						%br
						= @customer.state
					.field
						%b Postal Code
						%br
						= @customer.postal_code