config/routes.rb
Broker88::Application.routes.draw do
  root :to => 'carriers#index'

  resources :carriers, :customers, :shippers

  resources :loads do
    get :autocomplete_carrier_name, :on => :collection
    get :autocomplete_customer_name, :on => :collection
    get :autocomplete_shipper_name, :on => :collection
  end

  resources :import do
    get :carrier
    get :load
    get :customer
  end 

end

app/models/shipper.rb
class Shipper
	include Mongoid::Document

	field :name
	field :status
	field :street_address
	field :unit_number
	field :city
	field :state
	field :country
	field :postal_code
	field :contact_id
	field :autocharge_id
	field :phone_number
	field :toll_free
	field :fax_number
	field :created_at
	field :updated_at

	referenced_in :load
end

app/controllers/shippers_controller.rb
class ShippersController < ApplicationController
	def index
		@shippers = Shipper.any_of({:name => Regexp.new("^#{params[:search]}.*", true)})
		@shipper = Shipper.first
	end

	def new
		@shippers = Shipper.all
		@shipper = Shipper.new
	end

	def show
		@shippers = Shipper.all
		@shipper = Shipper.find(params[:id])
	end

	def create
		@shipper = Shipper.new(params[:shipper])

		if @shipper.save
			redirect_to shippers_path, notice: 'Shipper successfully created!'
		else
			render :action => 'new'
		end
	end

	def destroy
		@shipper = Shipper.find(params[:id])

		@customer.destroy
		redirect_to shippers_path, notice: 'Shipper deleted'
	end
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/views/shippers/index.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Name
				%th City
				%th State
				%th Phone Number
				%th Toll Free
				%th Fax Number
				%th
		%tbody
			- @shippers.each do |shipper|
				%tr
					%td= shipper.name
					%td= shipper.city
					%td= shipper.state
					%td= shipper.phone_number
					%td= shipper.toll_free
					%td= shipper.fax_number
					%td
						= link_to shipper_path(shipper), :class => 'pjax'  do
							%i.icon-search
						= link_to shipper_path(shipper), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		- if @shipper.nil?
			.alert.alert-error
				No Results
				.pull-right= link_to 'Clear Search', shippers_path
		-else
			.well-header
				= @shipper.name
			.well
				.row-fluid
					.span6
						.field
							%b Unit #
							%br
							= @shipper.unit_number
						.field
							%b City
							%br
							= @shipper.city
						.field
							%b Country
							%br
							= @shipper.country
					.span6
						.field
							%b Address
							%br
							= @shipper.street_address
						.field
							%b State
							%br
							= @shipper.state
						.field
							%b Postal Code
							%br
							= @shipper.postal_code

app/views/shippers/new.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Name
				%th City
				%th State
				%th Phone Number
				%th Toll Free
				%th Fax Number
				%th
		%tbody
			- @shippers.each do |shipper|
				%tr
					%td= shipper.name
					%td= shipper.city
					%td= shipper.state
					%td= shipper.phone_number
					%td= shipper.toll_free
					%td= shipper.fax_number
					%td
						= link_to shipper_path(shipper), :class => 'pjax' do
							%i.icon-search
						= link_to shipper_path(shipper), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		.well-header
			New shipper
		.well
			= form_for @shipper do |f|
				.row-fluid
					.span6
						.field
							= f.label :status
							= f.text_field :status
				.row-fluid
					.span12
						.field.full
							= f.label :name
							= f.text_field :name
				.row-fluid
					.span6
						.field
							= f.label :phone_number
							= f.text_field :phone_number
						.field
							= f.label :toll_free
							= f.text_field :toll_free
						.field
							= f.label :unit_number
							= f.text_field :unit_number
						.field
							= f.label :city
							= f.text_field :city
						.field
							= f.label :country
							= f.text_field :country
					.span6
						.field
							= f.label :fax_number
							= f.text_field :fax_number
						.field
							= f.label :street_address
							= f.text_field :street_address
						.field
							= f.label :state
							= f.text_field :state
						.field
							= f.label :postal_code
							= f.text_field :postal_code
				%br
				.row-fluid
					.span8
						%br
					.span4
						.actions
							= f.submit 'Save', :class => 'btn btn-primary'
							= link_to :action => "index" do
								%span.btn.btn-primary Cancel

app/views/shippers/show.html.haml
.span7
	%table.table
		%thead
			%tr
				%th Name
				%th City
				%th State
				%th Phone Number
				%th Toll Free
				%th Fax Number
				%th
		%tbody
			- @shippers.each do |shipper|
				%tr
					%td= shipper.name
					%td= shipper.city
					%td= shipper.state
					%td= shipper.phone_number
					%td= shipper.toll_free
					%td= shipper.fax_number
					%td
						= link_to shipper_path(shipper), :class => 'pjax'  do
							%i.icon-search
						= link_to shipper_path(shipper), method: :delete, :confirm => 'Are you sure?' do
							%i.icon-remove
.span5
	.sidebar{:data => {"pjax-container" => true}}
		.well-header
			= @shipper.name
		.well
			.row-fluid
				.span6
					.field
						%b Unit #
						%br
						= @shipper.unit_number
					.field
						%b City
						%br
						= @shipper.city
					.field
						%b Country
						%br
						= @shipper.country
				.span6
					.field
						%b Address
						%br
						= @shipper.street_address
					.field
						%b State
						%br
						= @shipper.state
					.field
						%b Postal Code
						%br
						= @shipper.postal_code