config/routes.rb
Broker88::Application.routes.draw do
  root :to => 'carriers#index'

  resources :carriers, :customers, :shippers

  resources :loads do
    get :autocomplete_carrier_name, :on => :collection
    get :autocomplete_customer_name, :on => :collection
    get :autocomplete_shipper_name, :on => :collection
  end

  resources :import do
    get :carrier
    get :load
    get :customer
  end 

end

app/views/layouts/application.html.haml
!!! html
%html
	%head
		%title Broker88
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags

%body
	.navbar.navbar-fixed-top
		.navbar-inner
			.container-fluid
				.row-fluid
					.brand
						Broker 88
					%ul.nav
						%li{:class => controller.controller_name == 'loads' ? 'active' : '' }= link_to 'Loads', loads_path
						%li{:class => controller.controller_name == 'carriers' ? 'active' : '' }= link_to 'Carriers', carriers_path
						%li{:class => controller.controller_name == 'customers' ? 'active' : ''}= link_to 'Customers', customers_path
						%li{:class => controller.controller_name == 'shippers' ? 'active': ''}= link_to 'Shippers', shippers_path
					= form_tag({:action => :index}, {:class => 'navbar-search pull-right', :method => :get})  do
						= text_field_tag :search, nil, :placeholder => 'Search'
					.actions.pull-right
						= render "actions/#{controller.action_name}"
					

	.container-fluid
		- flash.each do |name, msg|
			.alert{:class => "#{name == :notice ? 'success' : 'error'}"}	
				%a.close{'data-dismiss' => 'alert'} x
				= msg
		.row-fluid
			= yield